# Generated by Django 4.2.6 on 2023-10-16 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=20, null=True)),
                ('credit_balance', models.PositiveIntegerField(blank=True, null=True)),
                ('pending_balance', models.PositiveIntegerField(blank=True, null=True)),
                ('total_paid', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(blank=True, max_length=50, null=True)),
                ('live_price', models.PositiveIntegerField(blank=True, null=True)),
                ('live_weight', models.PositiveIntegerField(blank=True, null=True)),
                ('purchase_dates', models.DateField(blank=True, null=True)),
                ('payment_terms', models.PositiveIntegerField(blank=True, null=True)),
                ('slaughter_dates', models.DateField(blank=True, null=True)),
                ('canal_price', models.PositiveIntegerField(blank=True, null=True)),
                ('canal_weight', models.PositiveIntegerField(blank=True, null=True)),
                ('other_expenses', models.TextField(blank=True, null=True)),
                ('total_price_purchase', models.PositiveIntegerField(blank=True, null=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='canales.providermodel')),
            ],
        ),
    ]
