# Generated by Django 4.2.6 on 2023-10-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canales', '0002_alter_providermodel_phone_otherexpensesmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalmodel',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
