# Generated by Django 4.2.6 on 2023-10-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canales', '0003_animalmodel_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalmodel',
            name='state',
            field=models.CharField(choices=[('alive', 'Alive'), ('processed', 'Processed')], default='alive', max_length=10),
        ),
    ]
