# Generated by Django 4.2.6 on 2023-10-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canales', '0004_animalmodel_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalmodel',
            name='payment_state',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
