# Generated by Django 4.2.6 on 2023-10-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_purchasermodel_outstanding_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasehistory',
            name='purchase_date',
            field=models.DateTimeField(null=True),
        ),
    ]
