# Generated by Django 4.2.6 on 2023-10-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_purchasehistory_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasehistory',
            name='payment',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
