# Generated by Django 4.2.6 on 2023-10-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_purchasehistory_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasehistory',
            name='payment',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
