# Generated by Django 4.2.6 on 2023-10-31 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_alter_purchasehistory_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='acounts_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_day', models.DateTimeField()),
                ('sale_day_cash', models.PositiveIntegerField()),
                ('sale_day_credit', models.PositiveIntegerField()),
                ('credit_day_payment', models.IntegerField()),
                ('total_income', models.PositiveIntegerField()),
                ('pending_account', models.IntegerField()),
                ('total_sale', models.PositiveIntegerField()),
            ],
        ),
    ]
