# Generated by Django 4.2.6 on 2023-11-01 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_alter_acounts_history_credit_day_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acounts_history',
            name='pending_account',
        ),
    ]
